using System.Collections.Generic;
using System.Xml;

/// <summary>
/// An action to be generated by the BattleCommand.
/// </summary>
public abstract class BattleCommandAction
{
    public static BattleCommandAction Parse(XmlElement actionInfo)
    {
        switch (actionInfo.Name)
        {
            case "damage": // Lose a percentage of max health
                return new BattleCommandDamageAction(actionInfo);
            case "move": // Move
                return new BattleCommandMoveAction(actionInfo);
            case "skill": // Use a skill
                return new BattleCommandSkillAction(actionInfo);
            case "end": // End turn
                return new BattleCommandEndTurnAction();
            /*
            case "item": // Use an item
                return null;
            case "mix": // Mix two reagents
                return null;
                */
        }

        throw new System.IO.FileLoadException("[BattleCommandSelection] Unrecognized action type \"" + actionInfo.Name + "\"");
    }

    public abstract BattleAction Construct(BattleAgent agent, Dictionary<string, object> selections);
}
